create table if not exists public.blessings (
  id bigint generated by default as identity primary key,
  name text,
  message text not null,
  approved boolean not null default false,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

alter table public.blessings enable row level security;

create policy "Allow public blessing inserts"
on public.blessings
for insert
to anon
with check (true);

create policy "Allow public blessing count reads"
on public.blessings
for select
to anon
using (true);

